### ISSUE TITLE
Add help

### ISSUE THREAD

**Issue by inann** [inann/groupmeSP#1]
Add a help command so that the bot will spew out its available commands. This may be more difficult than it seems initially since we want it to be able to track new commands; that can either be left as part of the adding process (by adding them manually) or by creating a smart way of adding them.

**Comment by inann** [comment]
Doing this the simpler way first, then getting creative.

**Comment by chartreusemongoose** [comment]
Mentioned in the groupme:

For clarity, the "command" section should read something like "command [text]" or "command <text>" so someone reading the help section would know that they should put text after "command".

**Comment by inann** [comment]
Fixed in branch issue-1-Adding-Help, merged this morning.
